/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'flight-plans': FlightPlan;
    'flight-plan-series': FlightPlanSery;
    'flight-plan-status-events': FlightPlanStatusEvent;
    'flight-plan-memberships': FlightPlanMembership;
    'flight-plan-membership-events': FlightPlanMembershipEvent;
    'flight-plan-tasks': FlightPlanTask;
    logs: Log;
    'registration-tokens': RegistrationToken;
    'invite-requests': InviteRequest;
    avatars: Avatar;
    'gallery-images': GalleryImage;
    'honor-badge-media': HonorBadgeMedia;
    'navigation-nodes': NavigationNode;
    notifications: Notification;
    'task-attachments': TaskAttachment;
    'roadmap-tiers': RoadmapTier;
    plans: Plan;
    'matrix-flight-plan-mutes': MatrixFlightPlanMute;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'flight-plans': FlightPlansSelect<false> | FlightPlansSelect<true>;
    'flight-plan-series': FlightPlanSeriesSelect<false> | FlightPlanSeriesSelect<true>;
    'flight-plan-status-events': FlightPlanStatusEventsSelect<false> | FlightPlanStatusEventsSelect<true>;
    'flight-plan-memberships': FlightPlanMembershipsSelect<false> | FlightPlanMembershipsSelect<true>;
    'flight-plan-membership-events': FlightPlanMembershipEventsSelect<false> | FlightPlanMembershipEventsSelect<true>;
    'flight-plan-tasks': FlightPlanTasksSelect<false> | FlightPlanTasksSelect<true>;
    logs: LogsSelect<false> | LogsSelect<true>;
    'registration-tokens': RegistrationTokensSelect<false> | RegistrationTokensSelect<true>;
    'invite-requests': InviteRequestsSelect<false> | InviteRequestsSelect<true>;
    avatars: AvatarsSelect<false> | AvatarsSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    'honor-badge-media': HonorBadgeMediaSelect<false> | HonorBadgeMediaSelect<true>;
    'navigation-nodes': NavigationNodesSelect<false> | NavigationNodesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'task-attachments': TaskAttachmentsSelect<false> | TaskAttachmentsSelect<true>;
    'roadmap-tiers': RoadmapTiersSelect<false> | RoadmapTiersSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'matrix-flight-plan-mutes': MatrixFlightPlanMutesSelect<false> | MatrixFlightPlanMutesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Determines access level within the crew portal.
   */
  role:
    | 'captain'
    | 'quartermaster'
    | 'sailing-master'
    | 'boatswain'
    | 'gunner'
    | 'carpenter'
    | 'surgeon'
    | 'master-at-arms'
    | 'cook'
    | 'seamen'
    | 'powder-monkey'
    | 'cabin-boy'
    | 'swabbie';
  /**
   * Marks QA/seed accounts that are excluded from Crew Quarters listings and user/activity metrics.
   */
  isTestUser?: boolean | null;
  /**
   * Canonical account classification used for long-term audience and metrics filtering.
   */
  accountType?: ('human' | 'test' | 'system' | 'integration') | null;
  /**
   * Preferred admin read mode (quartermaster+ only, clamped by role on authenticated API requests).
   */
  adminModeViewPreference?: boolean | null;
  /**
   * Preferred admin edit mode (captain only, requires admin visibility and is clamped by role).
   */
  adminModeEditPreference?: boolean | null;
  /**
   * Immutable after registration. Use for the crew roster only.
   */
  firstName: string;
  /**
   * Immutable after registration. Use for the crew roster only.
   */
  lastName: string;
  /**
   * Stable crew URL (auto-generated).
   */
  profileSlug: string;
  /**
   * Crew nickname visible on the public profile.
   */
  callSign?: string | null;
  /**
   * Optional pronouns (e.g., they/them).
   */
  pronouns?: string | null;
  /**
   * Crew portrait stored within Payload.
   */
  avatar?: (number | null) | Avatar;
  /**
   * Optional absolute URL used when no upload is provided.
   */
  avatarUrl?: string | null;
  /**
   * Explicit media mode used when an avatar URL points to non-image media.
   */
  avatarMediaType?: ('image' | 'video' | 'model') | null;
  /**
   * Short biography shown on the profile page.
   */
  bio?: string | null;
  /**
   * Automatically updated when the crew member logs in or posts activity.
   */
  lastActiveAt?: string | null;
  /**
   * Automatically updated with the most recent page the crew member visited.
   */
  currentRoute?: string | null;
  /**
   * Highlight key skills or specialisations.
   */
  skills?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional external links (portfolio, socials, etc.).
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Recognition automatically granted for key crew milestones.
   */
  honorBadges?:
    | {
        code: string;
        awardedAt: string;
        source: 'automatic' | 'manual';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ELSAT balance; managed automatically by invites + weekly refill.
   */
  elsaTokens?: number | null;
  /**
   * Each crew member can invite one new pirate. Values are managed automatically.
   */
  invite?: {
    /**
     * Indicates how this invite slot is being used.
     */
    purpose?: ('recruit' | 'password_reset') | null;
    /**
     * Account the secure link affects (password resets only).
     */
    targetUser?: (number | null) | User;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    callSignSnapshot?: string | null;
    profileSlugSnapshot?: string | null;
    tokenId?: string | null;
    token?: string | null;
    sentAt?: string | null;
    expiresAt?: string | null;
    redeemedAt?: string | null;
    invitedUser?: (number | null) | User;
    /**
     * Indicates whether the secure link is ever rendered in the UI.
     */
    linkHidden?: boolean | null;
  };
  /**
   * Crew member who issued the invite for this pirate.
   */
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars".
 */
export interface Avatar {
  id: number;
  /**
   * Optional descriptive text for assistive technologies.
   */
  alt?: string | null;
  uploadedBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Matches the public route, e.g., gangway/about or bridge.
   */
  path: string;
  /**
   * Optional short blurb for search or previews.
   */
  summary?: string | null;
  /**
   * Defines who can read this page. Leave empty for the default public page behavior.
   */
  accessPolicy?: {
    mode?: ('public' | 'role' | 'private') | null;
    roleSpace?: 'crew' | null;
    /**
     * Examples: Crew · Cook or Flight plan · Passenger.
     */
    minimumRole?:
      | (
          | 'captain'
          | 'quartermaster'
          | 'sailing-master'
          | 'boatswain'
          | 'gunner'
          | 'carpenter'
          | 'surgeon'
          | 'master-at-arms'
          | 'cook'
          | 'seamen'
          | 'powder-monkey'
          | 'cabin-boy'
          | 'swabbie'
        )
      | null;
  };
  /**
   * Keep in sync with navigation nodes; label/description are optional overrides.
   */
  navigation?: {
    nodeId?:
      | (
          | 'arch'
          | 'flight'
          | 'bridge'
          | 'log'
          | 'gangway'
          | 'airlock'
          | 'about'
          | 'pirates'
          | 'legal'
          | 'contact'
          | 'crew'
          | 'lair'
          | 'engineering'
          | 'control'
          | 'bay'
        )
      | null;
    label?: string | null;
    description?: string | null;
  };
  layout: (
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        eyebrow?: string | null;
        title: string;
        tagline?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        ctas?:
          | {
              label: string;
              href: string;
              style?: ('primary' | 'secondary' | 'link') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        columns?: ('one' | 'two' | 'three') | null;
        cards: {
          variant?: ('static' | 'flightPlans' | 'logs' | 'links') | null;
          badge?: string | null;
          title: string;
          body?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          ctas?:
            | {
                label: string;
                href: string;
                style?: ('primary' | 'secondary' | 'link') | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Optional settings for dynamic cards (variant dependent).
           */
          config?: {
            limit?: number | null;
            minRole?:
              | (
                  | 'captain'
                  | 'quartermaster'
                  | 'sailing-master'
                  | 'boatswain'
                  | 'gunner'
                  | 'carpenter'
                  | 'surgeon'
                  | 'master-at-arms'
                  | 'cook'
                  | 'seamen'
                  | 'powder-monkey'
                  | 'cabin-boy'
                  | 'swabbie'
                )
              | null;
            emptyLabel?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGrid';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items: {
          heading: string;
          timestamp?: string | null;
          body?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Provide at least one media item with descriptive alt text.
         */
        slides: {
          /**
           * Optional heading shown with the image.
           */
          title?: string | null;
          /**
           * Describe the media for screen readers.
           */
          imageAlt: string;
          /**
           * Use Upload by default. Switch to External URL when needed.
           */
          imageType: 'upload' | 'url';
          /**
           * Media kind controls preview and playback. Uploads are auto-detected but can be overridden.
           */
          mediaType: 'image' | 'video' | 'audio' | 'model';
          /**
           * Upload or select a file stored within Payload.
           */
          galleryImage?: (number | null) | GalleryImage;
          /**
           * Full HTTP(S) media URL.
           */
          imageUrl?: string | null;
          /**
           * Optional short tag shown in navigation dots.
           */
          label?: string | null;
          caption?: string | null;
          creditLabel?: string | null;
          creditUrl?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageCarousel';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items: {
          title: string;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          cta?: {
            label?: string | null;
            href?: string | null;
            style?: ('primary' | 'secondary' | 'link') | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaList';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        intro?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        stats: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        ctas?:
          | {
              label: string;
              href: string;
              style?: ('primary' | 'secondary' | 'link') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statGrid';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        minRole?:
          | (
              | 'captain'
              | 'quartermaster'
              | 'sailing-master'
              | 'boatswain'
              | 'gunner'
              | 'carpenter'
              | 'surgeon'
              | 'master-at-arms'
              | 'cook'
              | 'seamen'
              | 'powder-monkey'
              | 'cabin-boy'
              | 'swabbie'
            )
          | null;
        limit?: number | null;
        cta: {
          label: string;
          href: string;
          style?: ('primary' | 'secondary' | 'link') | null;
          id?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'crewPreview';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        badge?: string | null;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        mode?: ('full' | 'preview') | null;
        /**
         * Caps the number of crew rendered (affects both modes).
         */
        limit?: number | null;
        ctas?:
          | {
              label: string;
              href: string;
              style?: ('primary' | 'secondary' | 'link') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'crewRoster';
      }
    | {
        /**
         * Optional override. Leave unset to inherit the page access policy.
         */
        accessPolicy?: {
          mode?: ('public' | 'role' | 'private') | null;
          roleSpace?: 'crew' | null;
          /**
           * Examples: Crew · Cook or Flight plan · Passenger.
           */
          minimumRole?:
            | (
                | 'captain'
                | 'quartermaster'
                | 'sailing-master'
                | 'boatswain'
                | 'gunner'
                | 'carpenter'
                | 'surgeon'
                | 'master-at-arms'
                | 'cook'
                | 'seamen'
                | 'powder-monkey'
                | 'cabin-boy'
                | 'swabbie'
              )
            | null;
        };
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Optional override; defaults to matching the current page path.
         */
        nodeId?:
          | (
              | 'arch'
              | 'flight'
              | 'bridge'
              | 'log'
              | 'gangway'
              | 'airlock'
              | 'about'
              | 'pirates'
              | 'legal'
              | 'contact'
              | 'crew'
              | 'lair'
              | 'engineering'
              | 'control'
              | 'bay'
            )
          | null;
        /**
         * Use when linking from a page that is not part of the ship layout tree.
         */
        path?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigationModule';
      }
  )[];
  /**
   * Crew member responsible for this entry.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gallery uploads used by missions and static pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Mission that owns this upload (leave empty for static pages).
   */
  flightPlan?: (number | null) | FlightPlan;
  /**
   * Static page that owns this upload (leave empty for missions).
   */
  page?: (number | null) | Page;
  uploadedBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    preview?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plans".
 */
export interface FlightPlan {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional manual ordering index matching legacy index.json ordering.
   */
  listOrder?: number | null;
  path: string;
  summary?: string | null;
  /**
   * Choose the mission category to help crews filter and browse flight plans.
   */
  category: 'project' | 'event' | 'test';
  /**
   * Canonical lifecycle status for mission planning and completion tracking.
   */
  status: 'planned' | 'pending' | 'ongoing' | 'on-hold' | 'postponed' | 'success' | 'failure' | 'aborted' | 'cancelled';
  statusChangedAt?: string | null;
  statusChangedBy?: (number | null) | User;
  statusReason?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  /**
   * Mission series grouping across iterations.
   */
  series?: (number | null) | FlightPlanSery;
  iterationNumber: number;
  previousIteration?: (number | null) | FlightPlan;
  location?: string | null;
  dateCode?: string | null;
  displayDate?: string | null;
  eventDate?: string | null;
  /**
   * Unified visibility preset. Detailed access policy is kept in sync below for inheritance and advanced overrides.
   */
  visibility?: ('public' | 'passengers' | 'crew' | 'captain') | null;
  /**
   * Canonical read access policy for this mission. Use crew role-space only for legacy compatibility scenarios.
   */
  accessPolicy?: {
    mode?: ('public' | 'role' | 'private') | null;
    roleSpace?: ('flight-plan' | 'crew') | null;
    /**
     * Examples: Crew · Cook or Flight plan · Passenger.
     */
    minimumRole?:
      | (
          | 'captain'
          | 'quartermaster'
          | 'sailing-master'
          | 'boatswain'
          | 'gunner'
          | 'carpenter'
          | 'surgeon'
          | 'master-at-arms'
          | 'cook'
          | 'seamen'
          | 'powder-monkey'
          | 'cabin-boy'
          | 'swabbie'
          | 'crew'
          | 'passenger'
        )
      | null;
  };
  /**
   * Override media view scope for mission gallery and task attachments. "Inherit" follows mission access policy; "Crew and captains only" blocks guests and anonymous viewers.
   */
  mediaVisibility?: ('inherit' | 'crew_only') | null;
  /**
   * When enabled, accepted crew organisers can promote passengers to crew.
   */
  crewCanPromotePassengers?: boolean | null;
  /**
   * When enabled, accepted passengers can create mission tasks and manage their own cards.
   */
  passengersCanCreateTasks?: boolean | null;
  /**
   * When enabled, accepted passengers can post and vote in mission task discussion threads. Crew-only tasks still block passenger access.
   */
  passengersCanCommentOnTasks?: boolean | null;
  /**
   * Public missions show roster details to everyone. Private missions stay hidden from outsiders and remain visible only to the captain, crew, and accepted passengers.
   */
  isPublic?: boolean | null;
  /**
   * When enabled, any authenticated crew account can view the mission, roster, and claim tasks for themselves. Captains still control edits and new task creation.
   */
  publicContributions?: boolean | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional reference media (images, videos, 3D models) to showcase the mission (max 8).
   */
  gallerySlides?:
    | {
        /**
         * Optional heading shown with the image.
         */
        title?: string | null;
        /**
         * Describe the media for screen readers.
         */
        imageAlt: string;
        /**
         * Use Upload by default. Switch to External URL when needed.
         */
        imageType: 'upload' | 'url';
        /**
         * Media kind controls preview and playback. Uploads are auto-detected but can be overridden.
         */
        mediaType: 'image' | 'video' | 'audio' | 'model';
        /**
         * Upload or select a file stored within Payload.
         */
        galleryImage?: (number | null) | GalleryImage;
        /**
         * Full HTTP(S) media URL.
         */
        imageUrl?: string | null;
        /**
         * Optional short tag shown in navigation dots.
         */
        label?: string | null;
        caption?: string | null;
        creditLabel?: string | null;
        creditUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Crew member responsible for this entry.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-series".
 */
export interface FlightPlanSery {
  id: number;
  slug: string;
  title: string;
  category: 'project' | 'event' | 'test';
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-status-events".
 */
export interface FlightPlanStatusEvent {
  id: number;
  flightPlan: number | FlightPlan;
  fromStatus?:
    | ('planned' | 'pending' | 'ongoing' | 'on-hold' | 'postponed' | 'success' | 'failure' | 'aborted' | 'cancelled')
    | null;
  toStatus:
    | 'planned'
    | 'pending'
    | 'ongoing'
    | 'on-hold'
    | 'postponed'
    | 'success'
    | 'failure'
    | 'aborted'
    | 'cancelled';
  reason?: string | null;
  changedBy?: (number | null) | User;
  changedAt: string;
  actionType: 'transition' | 'reopen' | 'normalize' | 'backfill';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-memberships".
 */
export interface FlightPlanMembership {
  id: number;
  flightPlan: number | FlightPlan;
  user: number | User;
  role: 'owner' | 'crew' | 'guest';
  /**
   * Current state of the invitation.
   */
  invitationStatus: 'pending' | 'accepted' | 'declined' | 'revoked';
  invitedBy: number | User;
  invitedAt: string;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-membership-events".
 */
export interface FlightPlanMembershipEvent {
  id: number;
  membership?: (number | null) | FlightPlanMembership;
  flightPlan: number | FlightPlan;
  user: number | User;
  eventType: string;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attempts: number;
  lastError?: string | null;
  queuedAt: string;
  lockedAt?: string | null;
  processedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-tasks".
 */
export interface FlightPlanTask {
  id: number;
  flightPlan: number | FlightPlan;
  /**
   * Short label for the task (max 120 characters).
   */
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Current stage of the task.
   */
  state: 'ideation' | 'grooming' | 'ready' | 'in-progress' | 'review' | 'done' | 'live';
  /**
   * Draft trigger for QA/ELSA tests (OnTouch, OnUpdate, Repeat tiers, or Never).
   */
  testRunCadence?: ('on-touch' | 'on-update' | 'repeat-1' | 'repeat-2' | 'repeat-3' | 'never') | null;
  /**
   * Used to sort tasks inside each state column.
   */
  listOrder?: number | null;
  ownerMembership: number | FlightPlanMembership;
  /**
   * Stored as membership ids; managed through the mission task APIs.
   */
  assigneeMembershipIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Managed via the mission task attachment APIs.
   */
  attachments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Managed via the mission task link APIs.
   */
  links?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Mask task content for passengers and contributors when enabled.
   */
  isCrewOnly?: boolean | null;
  /**
   * Auto-incremented by the mission task APIs.
   */
  version: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs".
 */
export interface Log {
  id: number;
  title: string;
  /**
   * Displayed log title (max 50 characters).
   */
  headline: string;
  slug: string;
  path: string;
  dateCode?: string | null;
  logDate?: string | null;
  body: string;
  /**
   * Optional mission this log pertains to.
   */
  flightPlan?: (number | null) | FlightPlan;
  /**
   * Captured when a mission is deleted so logs can show the former mission details.
   */
  flightPlanTombstone?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Crew member responsible for this entry.
   */
  owner?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-tokens".
 */
export interface RegistrationToken {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  purpose: 'recruit' | 'password_reset';
  /**
   * Account this token acts on (password resets only).
   */
  targetUser?: (number | null) | User;
  /**
   * Crew member who issued this invite token.
   */
  inviter?: (number | null) | User;
  token: string;
  expiresAt: string;
  used?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-requests".
 */
export interface InviteRequest {
  id: number;
  ip: string;
  userAgent?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload-backed media assets for honor badges.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "honor-badge-media".
 */
export interface HonorBadgeMedia {
  id: number;
  /**
   * Honor badge code this media asset is attached to.
   */
  badgeCode: 'pioneer';
  /**
   * Optional descriptive text for assistive technologies.
   */
  alt?: string | null;
  uploadedBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-nodes".
 */
export interface NavigationNode {
  id: number;
  nodeId:
    | 'arch'
    | 'flight'
    | 'bridge'
    | 'log'
    | 'gangway'
    | 'airlock'
    | 'about'
    | 'pirates'
    | 'legal'
    | 'contact'
    | 'crew'
    | 'lair'
    | 'engineering'
    | 'control'
    | 'bay';
  /**
   * Override label displayed in navigation and menu.
   */
  label: string;
  /**
   * Optional tooltip/description for this node.
   */
  description?: string | null;
  /**
   * Automatically managed path of the linked page (if any).
   */
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  event: string;
  recipient: number | User;
  actor?: (number | null) | User;
  message: string;
  ctaUrl?: string | null;
  ctaLabel?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mission task uploads and reference files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-attachments".
 */
export interface TaskAttachment {
  id: number;
  flightPlan: number | FlightPlan;
  task: number | FlightPlanTask;
  uploadedBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-tiers".
 */
export interface RoadmapTier {
  id: number;
  /**
   * Stable identifier such as tier1, tier2, tier3, tier4, or tier5.
   */
  tierId: string;
  tier: 'tier1' | 'tier2' | 'tier3' | 'tier4' | 'tier5';
  title: string;
  description?: string | null;
  /**
   * Tier-level read access. Items inherit this policy unless they define an override.
   */
  accessPolicy?: {
    mode?: ('public' | 'role' | 'private') | null;
    roleSpace?: 'crew' | null;
    /**
     * Examples: Crew · Cook or Flight plan · Passenger.
     */
    minimumRole?:
      | (
          | 'captain'
          | 'quartermaster'
          | 'sailing-master'
          | 'boatswain'
          | 'gunner'
          | 'carpenter'
          | 'surgeon'
          | 'master-at-arms'
          | 'cook'
          | 'seamen'
          | 'powder-monkey'
          | 'cabin-boy'
          | 'swabbie'
        )
      | null;
  };
  /**
   * Optional short focus statement for the tier.
   */
  focus?: string | null;
  /**
   * Optional summary such as “✅ 3 shipped • ⚙️ 1 active • 🧭 2 queued”.
   */
  statusSummary?: string | null;
  items: {
    /**
     * Identifier such as T2.06. Shown on Control and used for ordering.
     */
    code: string;
    title: string;
    summary?: string | null;
    /**
     * Optional item override. If empty, inherits tier-level policy.
     */
    accessPolicy?: {
      mode?: ('public' | 'role' | 'private') | null;
      roleSpace?: 'crew' | null;
      /**
       * Examples: Crew · Cook or Flight plan · Passenger.
       */
      minimumRole?:
        | (
            | 'captain'
            | 'quartermaster'
            | 'sailing-master'
            | 'boatswain'
            | 'gunner'
            | 'carpenter'
            | 'surgeon'
            | 'master-at-arms'
            | 'cook'
            | 'seamen'
            | 'powder-monkey'
            | 'cabin-boy'
            | 'swabbie'
          )
        | null;
    };
    status: 'queued' | 'active' | 'shipped' | 'tested' | 'canceled';
    cloudStatus: 'pending' | 'deploying' | 'healthy';
    /**
     * Optional label for a supporting doc or link.
     */
    referenceLabel?: string | null;
    /**
     * Doc or plan URL (accepts relative repo paths).
     */
    referenceUrl?: string | null;
    /**
     * Optional link back to the plan document.
     */
    plan?: {
      id?: string | null;
      title?: string | null;
      owner?: string | null;
      /**
       * Relative repo path (docs/...) or full URL.
       */
      path?: string | null;
      status?: ('queued' | 'active' | 'shipped' | 'tested' | 'canceled') | null;
      cloudStatus?: ('pending' | 'deploying' | 'healthy') | null;
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Stable identifier such as plan-archive-cms or T2.20-plan-archive.
   */
  planId: string;
  /**
   * Used for detail page URLs, typically matches plan id.
   */
  slug: string;
  title: string;
  owner: string;
  tier: 'tier1' | 'tier2' | 'tier3' | 'tier4' | 'tier5' | 'platform' | 'support' | 'meta';
  status: 'queued' | 'active' | 'shipped' | 'tested' | 'canceled';
  cloudStatus: 'pending' | 'deploying' | 'healthy';
  summary?: string | null;
  /**
   * String such as 2025-12-05; keep in sync with roadmap doc.
   */
  lastUpdated?: string | null;
  /**
   * Relative repo path (docs/...) or external URL for the plan document.
   */
  path?: string | null;
  links?:
    | {
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matrix-flight-plan-mutes".
 */
export interface MatrixFlightPlanMute {
  id: number;
  recordKey: string;
  user: number | User;
  flightPlan: number | FlightPlan;
  muted: boolean;
  mutedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'flight-plans';
        value: number | FlightPlan;
      } | null)
    | ({
        relationTo: 'flight-plan-series';
        value: number | FlightPlanSery;
      } | null)
    | ({
        relationTo: 'flight-plan-status-events';
        value: number | FlightPlanStatusEvent;
      } | null)
    | ({
        relationTo: 'flight-plan-memberships';
        value: number | FlightPlanMembership;
      } | null)
    | ({
        relationTo: 'flight-plan-membership-events';
        value: number | FlightPlanMembershipEvent;
      } | null)
    | ({
        relationTo: 'flight-plan-tasks';
        value: number | FlightPlanTask;
      } | null)
    | ({
        relationTo: 'logs';
        value: number | Log;
      } | null)
    | ({
        relationTo: 'registration-tokens';
        value: number | RegistrationToken;
      } | null)
    | ({
        relationTo: 'invite-requests';
        value: number | InviteRequest;
      } | null)
    | ({
        relationTo: 'avatars';
        value: number | Avatar;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'honor-badge-media';
        value: number | HonorBadgeMedia;
      } | null)
    | ({
        relationTo: 'navigation-nodes';
        value: number | NavigationNode;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'task-attachments';
        value: number | TaskAttachment;
      } | null)
    | ({
        relationTo: 'roadmap-tiers';
        value: number | RoadmapTier;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'matrix-flight-plan-mutes';
        value: number | MatrixFlightPlanMute;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  isTestUser?: T;
  accountType?: T;
  adminModeViewPreference?: T;
  adminModeEditPreference?: T;
  firstName?: T;
  lastName?: T;
  profileSlug?: T;
  callSign?: T;
  pronouns?: T;
  avatar?: T;
  avatarUrl?: T;
  avatarMediaType?: T;
  bio?: T;
  lastActiveAt?: T;
  currentRoute?: T;
  skills?:
    | T
    | {
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  honorBadges?:
    | T
    | {
        code?: T;
        awardedAt?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  elsaTokens?: T;
  invite?:
    | T
    | {
        purpose?: T;
        targetUser?: T;
        firstName?: T;
        lastName?: T;
        email?: T;
        callSignSnapshot?: T;
        profileSlugSnapshot?: T;
        tokenId?: T;
        token?: T;
        sentAt?: T;
        expiresAt?: T;
        redeemedAt?: T;
        invitedUser?: T;
        linkHidden?: T;
      };
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  summary?: T;
  accessPolicy?:
    | T
    | {
        mode?: T;
        roleSpace?: T;
        minimumRole?: T;
      };
  navigation?:
    | T
    | {
        nodeId?: T;
        label?: T;
        description?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              eyebrow?: T;
              title?: T;
              tagline?: T;
              body?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              intro?: T;
              columns?: T;
              cards?:
                | T
                | {
                    variant?: T;
                    badge?: T;
                    title?: T;
                    body?: T;
                    ctas?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          style?: T;
                          id?: T;
                        };
                    config?:
                      | T
                      | {
                          limit?: T;
                          minRole?: T;
                          emptyLabel?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              intro?: T;
              items?:
                | T
                | {
                    heading?: T;
                    timestamp?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageCarousel?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              intro?: T;
              slides?:
                | T
                | {
                    title?: T;
                    imageAlt?: T;
                    imageType?: T;
                    mediaType?: T;
                    galleryImage?: T;
                    imageUrl?: T;
                    label?: T;
                    caption?: T;
                    creditLabel?: T;
                    creditUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaList?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          style?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statGrid?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              intro?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        crewPreview?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              description?: T;
              minRole?: T;
              limit?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        crewRoster?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              badge?: T;
              title?: T;
              description?: T;
              mode?: T;
              limit?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        navigationModule?:
          | T
          | {
              accessPolicy?:
                | T
                | {
                    mode?: T;
                    roleSpace?: T;
                    minimumRole?: T;
                  };
              title?: T;
              description?: T;
              nodeId?: T;
              path?: T;
              id?: T;
              blockName?: T;
            };
      };
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plans_select".
 */
export interface FlightPlansSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  listOrder?: T;
  path?: T;
  summary?: T;
  category?: T;
  status?: T;
  statusChangedAt?: T;
  statusChangedBy?: T;
  statusReason?: T;
  startedAt?: T;
  finishedAt?: T;
  series?: T;
  iterationNumber?: T;
  previousIteration?: T;
  location?: T;
  dateCode?: T;
  displayDate?: T;
  eventDate?: T;
  visibility?: T;
  accessPolicy?:
    | T
    | {
        mode?: T;
        roleSpace?: T;
        minimumRole?: T;
      };
  mediaVisibility?: T;
  crewCanPromotePassengers?: T;
  passengersCanCreateTasks?: T;
  passengersCanCommentOnTasks?: T;
  isPublic?: T;
  publicContributions?: T;
  body?: T;
  gallerySlides?:
    | T
    | {
        title?: T;
        imageAlt?: T;
        imageType?: T;
        mediaType?: T;
        galleryImage?: T;
        imageUrl?: T;
        label?: T;
        caption?: T;
        creditLabel?: T;
        creditUrl?: T;
        id?: T;
      };
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-series_select".
 */
export interface FlightPlanSeriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-status-events_select".
 */
export interface FlightPlanStatusEventsSelect<T extends boolean = true> {
  flightPlan?: T;
  fromStatus?: T;
  toStatus?: T;
  reason?: T;
  changedBy?: T;
  changedAt?: T;
  actionType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-memberships_select".
 */
export interface FlightPlanMembershipsSelect<T extends boolean = true> {
  flightPlan?: T;
  user?: T;
  role?: T;
  invitationStatus?: T;
  invitedBy?: T;
  invitedAt?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-membership-events_select".
 */
export interface FlightPlanMembershipEventsSelect<T extends boolean = true> {
  membership?: T;
  flightPlan?: T;
  user?: T;
  eventType?: T;
  payload?: T;
  attempts?: T;
  lastError?: T;
  queuedAt?: T;
  lockedAt?: T;
  processedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-plan-tasks_select".
 */
export interface FlightPlanTasksSelect<T extends boolean = true> {
  flightPlan?: T;
  title?: T;
  description?: T;
  state?: T;
  testRunCadence?: T;
  listOrder?: T;
  ownerMembership?: T;
  assigneeMembershipIds?: T;
  attachments?: T;
  links?: T;
  isCrewOnly?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logs_select".
 */
export interface LogsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  path?: T;
  dateCode?: T;
  logDate?: T;
  body?: T;
  flightPlan?: T;
  flightPlanTombstone?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-tokens_select".
 */
export interface RegistrationTokensSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  purpose?: T;
  targetUser?: T;
  inviter?: T;
  token?: T;
  expiresAt?: T;
  used?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-requests_select".
 */
export interface InviteRequestsSelect<T extends boolean = true> {
  ip?: T;
  userAgent?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars_select".
 */
export interface AvatarsSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  flightPlan?: T;
  page?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        preview?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "honor-badge-media_select".
 */
export interface HonorBadgeMediaSelect<T extends boolean = true> {
  badgeCode?: T;
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-nodes_select".
 */
export interface NavigationNodesSelect<T extends boolean = true> {
  nodeId?: T;
  label?: T;
  description?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  event?: T;
  recipient?: T;
  actor?: T;
  message?: T;
  ctaUrl?: T;
  ctaLabel?: T;
  metadata?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-attachments_select".
 */
export interface TaskAttachmentsSelect<T extends boolean = true> {
  flightPlan?: T;
  task?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-tiers_select".
 */
export interface RoadmapTiersSelect<T extends boolean = true> {
  tierId?: T;
  tier?: T;
  title?: T;
  description?: T;
  accessPolicy?:
    | T
    | {
        mode?: T;
        roleSpace?: T;
        minimumRole?: T;
      };
  focus?: T;
  statusSummary?: T;
  items?:
    | T
    | {
        code?: T;
        title?: T;
        summary?: T;
        accessPolicy?:
          | T
          | {
              mode?: T;
              roleSpace?: T;
              minimumRole?: T;
            };
        status?: T;
        cloudStatus?: T;
        referenceLabel?: T;
        referenceUrl?: T;
        plan?:
          | T
          | {
              id?: T;
              title?: T;
              owner?: T;
              path?: T;
              status?: T;
              cloudStatus?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  planId?: T;
  slug?: T;
  title?: T;
  owner?: T;
  tier?: T;
  status?: T;
  cloudStatus?: T;
  summary?: T;
  lastUpdated?: T;
  path?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matrix-flight-plan-mutes_select".
 */
export interface MatrixFlightPlanMutesSelect<T extends boolean = true> {
  recordKey?: T;
  user?: T;
  flightPlan?: T;
  muted?: T;
  mutedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}