import { test, expect } from '@playwright/test';

const defaultApiBase = process.env.CI === 'true' ? 'http://cms:3000' : 'http://localhost:3000';
const resolveApiBase = () =>
  process.env.PLAYWRIGHT_API_BASE ?? process.env.ASTRAL_API_BASE ?? defaultApiBase;

const buildApiUrl = (path: string) => {
  const base = resolveApiBase();
  try {
    return new URL(path, base).toString();
  } catch {
    return `${base.replace(/\/$/, '')}${path}`;
  }
};

const currentTimestamp = () => new Date().toISOString();
const envFlagEnabled = (value?: string) => ['1', 'true', 'yes', 'on'].includes((value ?? '').toLowerCase());

test.describe('Flight plan collaboration permissions', () => {
  test('only captains invite and guests must accept', async ({ request }) => {
    const captainToken = process.env.PLAYWRIGHT_CAPTAIN_TOKEN;
    const crewToken = process.env.PLAYWRIGHT_CREW_TOKEN;
    const crewSlug = process.env.PLAYWRIGHT_CREW_SLUG;
    const runCollab = envFlagEnabled(process.env.PLAYWRIGHT_RUN_COLLAB);

    test.skip(
      !runCollab || !captainToken || !crewToken || !crewSlug,
      'Set PLAYWRIGHT_RUN_COLLAB=1 and provide PLAYWRIGHT_CAPTAIN_TOKEN, PLAYWRIGHT_CREW_TOKEN, and PLAYWRIGHT_CREW_SLUG to run this test.',
    );

    const createResponse = await request.post(buildApiUrl('/api/flight-plans'), {
      headers: { Authorization: `Bearer ${captainToken}` },
      data: {
        title: `Automated mission ${currentTimestamp()}`,
        summary: 'Automated QA',
        location: 'Test Dock',
        eventDate: new Date().toISOString().slice(0, 10),
        body: [
          {
            type: 'paragraph',
            children: [{ text: 'Generated by flight plan collaboration spec.' }],
          },
        ],
      },
    });
    expect(createResponse.status(), 'captain should be able to create missions').toBe(201);
    const planPayload = await createResponse.json();
    const slug = planPayload?.plan?.slug;
    expect(slug, 'created plan should include a slug').toBeTruthy();

    const inviteResponse = await request.post(
      buildApiUrl(`/api/flight-plans/${encodeURIComponent(slug)}/members`),
      {
        headers: { Authorization: `Bearer ${captainToken}` },
        data: { slug: crewSlug },
      },
    );
    expect(inviteResponse.status(), 'captain invites should succeed').toBe(201);
    const invitePayload = await inviteResponse.json();
    const membershipId = invitePayload?.membership?.id;
    expect(membershipId, 'invitation should return a membership id').toBeTruthy();

    const forbiddenResponse = await request.post(
      buildApiUrl(`/api/flight-plans/${encodeURIComponent(slug)}/members`),
      {
        headers: { Authorization: `Bearer ${crewToken}` },
        data: { slug: crewSlug },
      },
    );
    expect(forbiddenResponse.status(), 'crew organisers cannot send invites').toBe(403);

    const acceptResponse = await request.patch(
      buildApiUrl(`/api/flight-plan-memberships/${membershipId}`),
      {
        headers: { Authorization: `Bearer ${crewToken}` },
        data: { action: 'accept' },
      },
    );
    expect(acceptResponse.status(), 'invitee should be able to accept their membership').toBe(200);
  });
});
