import { test, expect, type APIRequestContext, type Locator, type Page } from '@playwright/test';

import { buildApiUrl, loginViaApi } from './support/api';
import { loginThroughUi } from './support/auth';
import { getSeededCaptain, type SeededAccount } from './support/fixtures';
import { openPageEditor } from './support/pageEditor';

const PNG_1X1_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO2nYHkAAAAASUVORK5CYII=';
const SHOULD_CLEANUP_DYNAMIC_FIXTURES =
  process.env.PLAYWRIGHT_CLEANUP_DYNAMIC_FIXTURES === '1' || process.env.CI !== 'true';
const CLEANUP_REQUEST_TIMEOUT_MS = 20_000;
const KEEP_SESSION_ALIVE_INTERVAL_MS = 12_000;
const GALLERY_SPEC_TIMEOUT_MS = process.env.CI ? 360_000 : 240_000;

const toRecord = (value: unknown): Record<string, unknown> | null =>
  value && typeof value === 'object' ? (value as Record<string, unknown>) : null;

const toNumericId = (value: unknown): number | null => {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim().length) {
    const parsed = Number.parseInt(value, 10);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
};

const expandAccordionItem = async (slideCard: Locator) => {
  const trigger = slideCard.locator('.ui-accordion__trigger').first();
  if ((await trigger.count()) === 0) return;
  await expect(trigger).toBeVisible({ timeout: 30_000 });
  const isExpanded = await trigger.getAttribute('aria-expanded');
  if (isExpanded !== 'true') {
    await trigger.click();
  }
};

const createFlightPlan = async (
  request: APIRequestContext,
  token: string,
  stamp: number,
): Promise<{ id: number; slug: string }> => {
  const response = await request.post(buildApiUrl('/api/flight-plans'), {
    headers: { Authorization: `Bearer ${token}` },
    data: {
      title: `Gallery persistence ${stamp}`,
      summary: 'Regression plan for gallery upload/reorder/remove persistence.',
      location: 'Playwright QA Dock',
      eventDate: new Date().toISOString().slice(0, 10),
      body: [{ type: 'paragraph', children: [{ text: 'Generated by gallery persistence e2e.' }] }],
    },
  });
  expect(response.status(), 'captain should create flight plan fixture').toBe(201);

  const payload = toRecord(await response.json()) ?? {};
  const plan = toRecord(payload.plan) ?? {};
  const id = toNumericId(plan.id);
  const slug = typeof plan.slug === 'string' ? plan.slug.trim() : '';
  expect(id, 'created flight plan should include numeric id').not.toBeNull();
  expect(slug, 'created flight plan should include slug').toBeTruthy();

  return { id: Number(id), slug };
};

const cleanupFlightPlan = async (request: APIRequestContext, token: string, slug: string) => {
  await request
    .delete(buildApiUrl(`/api/flight-plans/${encodeURIComponent(slug)}`), {
      headers: { Authorization: `Bearer ${token}` },
      timeout: CLEANUP_REQUEST_TIMEOUT_MS,
    })
    .catch(() => null);
};

const createPageWithCarousel = async (
  request: APIRequestContext,
  token: string,
  stamp: number,
): Promise<{ id: number; path: string }> => {
  const path = `playwright-gallery-persistence-${stamp}`;
  const response = await request.post(buildApiUrl('/api/pages'), {
    headers: { Authorization: `Bearer ${token}` },
    data: {
      title: `Gallery persistence page ${stamp}`,
      path,
      layout: [
        {
          blockType: 'imageCarousel',
          title: 'Persistence gallery',
          intro: [],
          slides: [
            {
              title: 'Base slide A',
              imageAlt: 'Base slide A alt',
              imageType: 'url',
              imageUrl: 'https://picsum.photos/seed/playwright-a/1200/800',
              caption: '',
            },
            {
              title: 'Base slide B',
              imageAlt: 'Base slide B alt',
              imageType: 'url',
              imageUrl: 'https://picsum.photos/seed/playwright-b/1200/800',
              caption: '',
            },
          ],
        },
      ],
    },
  });
  expect(response.status(), 'captain should create page fixture').toBe(201);

  const payload = toRecord(await response.json()) ?? {};
  const document = toRecord(payload.doc) ?? payload;
  const id = toNumericId(document.id);
  const resolvedPath = typeof document.path === 'string' ? document.path.trim() : path;
  expect(id, 'created page should include numeric id').not.toBeNull();
  expect(resolvedPath, 'created page should include path').toBeTruthy();

  return { id: Number(id), path: resolvedPath };
};

const cleanupPage = async (request: APIRequestContext, token: string, pageId: number) => {
  await request
    .delete(buildApiUrl(`/api/pages/${encodeURIComponent(String(pageId))}`), {
      headers: { Authorization: `Bearer ${token}` },
      timeout: CLEANUP_REQUEST_TIMEOUT_MS,
    })
    .catch(() => null);
};

const dismissSessionWarning = async (page: Page) => {
  const warning = page.getByText(/You get automatically thrown off ship/i).first();
  if (!(await warning.isVisible().catch(() => false))) return;
  const stayButton = page.getByRole('button', { name: 'Stay on deck' });
  if (await stayButton.isVisible().catch(() => false)) {
    await stayButton.click().catch(() => null);
  }
};

const keepSessionAlive = async (page: Page) => {
  await dismissSessionWarning(page);
  await page
    .evaluate(() => {
      window.dispatchEvent(
        new MouseEvent('mousemove', { bubbles: true, clientX: 12, clientY: 12 }),
      );
      window.dispatchEvent(new Event('scroll', { bubbles: true }));
    })
    .catch(() => null);
};

const withSessionKeepAlive = async <T>(page: Page, operation: () => Promise<T>): Promise<T> => {
  await keepSessionAlive(page);
  const interval = setInterval(() => {
    void keepSessionAlive(page);
  }, KEEP_SESSION_ALIVE_INTERVAL_MS);
  try {
    return await operation();
  } finally {
    clearInterval(interval);
  }
};

const waitForFlightPlanPatch = async (page: Page, slug: string) => {
  const encodedSlug = encodeURIComponent(slug);
  const slugPath = `/api/flight-plans/${encodedSlug}`;
  try {
    const response = await withSessionKeepAlive(page, () =>
      page.waitForResponse(
        (response) => {
          const method = response.request().method();
          if (method !== 'PATCH' && method !== 'PUT') return false;
          const url = response.url();
          return url.includes(slugPath) || url.includes('/api/flight-plans/');
        },
        { timeout: 20_000 },
      ),
    );
    expect(
      response.ok(),
      `flight plan mutation should succeed for ${slug} (status ${response.status()})`,
    ).toBeTruthy();
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    if (/timeout/i.test(message)) {
      test
        .info()
        .annotations.push({
          type: 'warning',
          description: `No explicit flight-plan mutation captured for ${slug}; continuing via persisted-state checks.`,
        });
      return;
    }
    throw error;
  }
};

const ensureFlightPlanAccess = async (
  page: Page,
  captain: SeededAccount,
  slug: string,
) => {
  const signInPrompt = page.getByText(/Sign in to view this mission/i).first();
  if (!(await signInPrompt.isVisible().catch(() => false))) return;
  test.info().annotations.push({
    type: 'warning',
    description: `Mission view required re-authentication for ${slug}; retrying login.`,
  });
  await loginThroughUi(page, captain, { landingPath: `/bridge/flight-plans/${slug}` });
  await dismissSessionWarning(page);
};

const recoverTransientFlightPlanFetchFailure = async (page: Page, slug: string) => {
  const editor = page.locator('.flight-plan-gallery-editor');
  const retryButton = page.getByRole('button', { name: 'Retry' }).first();
  const fetchFailure = page
    .getByText(/\/api\/flight-plans\?[^"]*slug=.*Failed to fetch/i)
    .first();

  for (let attempt = 1; attempt <= 3; attempt += 1) {
    if (await editor.isVisible().catch(() => false)) return;

    const hasFetchFailure = await fetchFailure.isVisible().catch(() => false);
    if (!hasFetchFailure) return;

    test.info().annotations.push({
      type: 'warning',
      description: `Flight-plan API fetch failed on load for ${slug}; retrying (${attempt}/3).`,
    });

    if (await retryButton.isVisible().catch(() => false)) {
      await retryButton.click();
    } else {
      await page.goto(`/bridge/flight-plans/${slug}`, { waitUntil: 'domcontentloaded' });
    }

    await keepSessionAlive(page);
    await page.waitForTimeout(1_000);
  }
};

const uploadFlightPlanImageWithRetry = async ({
  page,
  editor,
  fileInput,
  stamp,
  suffix,
  expectedCount,
}: {
  page: Page;
  editor: Locator;
  fileInput: Locator;
  stamp: number;
  suffix: string;
  expectedCount: number;
}) => {
  const slideCards = editor.locator('.gallery-slide-editor');
  for (let attempt = 1; attempt <= 2; attempt += 1) {
    await fileInput.setInputFiles({
      name: `flight-plan-${suffix}-${stamp}.png`,
      mimeType: 'image/png',
      buffer: Buffer.from(PNG_1X1_BASE64, 'base64'),
    });

    try {
      await withSessionKeepAlive(page, () =>
        expect(slideCards).toHaveCount(expectedCount, { timeout: 45_000 }),
      );
      return;
    } catch (error) {
      const timeoutAlertVisible = await editor
        .getByText(/Upload timed out after/i)
        .first()
        .isVisible()
        .catch(() => false);
      if (attempt < 2 && timeoutAlertVisible) {
        test.info().annotations.push({
          type: 'warning',
          description: `Upload attempt ${attempt} timed out; retrying once.`,
        });
        await keepSessionAlive(page);
        continue;
      }
      throw error;
    }
  }
};

const waitForPagePatch = async (page: Page, pageId: number) => {
  const pagePath = `/api/pages/${encodeURIComponent(String(pageId))}`;
  try {
    const response = await withSessionKeepAlive(page, () =>
      page.waitForResponse(
        (response) => {
          const method = response.request().method();
          if (method !== 'PATCH' && method !== 'PUT') return false;
          const url = response.url();
          return url.includes(pagePath) || url.includes('/api/pages/');
        },
        { timeout: 20_000 },
      ),
    );
    expect(
      response.ok(),
      `page mutation should succeed for ${pageId} (status ${response.status()})`,
    ).toBeTruthy();
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    if (/timeout/i.test(message)) {
      test
        .info()
        .annotations.push({
          type: 'warning',
          description: `No explicit page mutation captured for ${pageId}; continuing via persisted-state checks.`,
        });
      return;
    }
    throw error;
  }
};

const waitForPageCarouselUploadsToFinish = async (carouselBlock: Locator) => {
  const uploadButtons = carouselBlock.getByTestId('page-carousel-upload-button');
  await expect
    .poll(
      async () => {
        const count = await uploadButtons.count();
        for (let index = 0; index < count; index += 1) {
          const label = ((await uploadButtons.nth(index).textContent()) ?? '').trim();
          if (/uploading/i.test(label)) {
            return 'uploading';
          }
        }
        return 'idle';
      },
      { timeout: 45_000, intervals: [250, 500, 1_000, 2_000] },
    )
    .toBe('idle');
};

const persistFlightPlanGalleryChanges = async (
  page: Page,
  editor: Locator,
  slug: string,
) => {
  const status = editor.locator('.flight-plan-gallery-editor__save .ui-text').first();
  const error = editor.locator('.flight-plan-gallery-editor__error').first();
  const saveButton = editor.getByRole('button', { name: 'Save gallery' });
  const settleTimeoutMs = 60_000;
  const startedAt = Date.now();
  let lastStatus = '';

  const waitForManualSaveReady = async (): Promise<{
    statusText: string;
    canClick: boolean;
  }> => {
    await expect
      .poll(
        async () => {
          const statusText = ((await status.textContent()) ?? '').trim();
          const canClick = await saveButton.isEnabled().catch(() => false);
          const unsaved = /^Unsaved changes\./i.test(statusText);
          if (canClick || !unsaved || statusText === 'Saved.') {
            return { statusText, canClick, state: 'ready' as const };
          }
          return { statusText, canClick, state: 'waiting' as const };
        },
        { timeout: 10_000, intervals: [250, 500, 1_000, 2_000] },
      )
      .toMatchObject({ state: 'ready' });

    const statusText = ((await status.textContent()) ?? '').trim();
    const canClick = await saveButton.isEnabled().catch(() => false);
    return { statusText, canClick };
  };

  while (Date.now() - startedAt < settleTimeoutMs) {
    await keepSessionAlive(page);

    if (await error.isVisible().catch(() => false)) {
      const message = (await error.textContent())?.trim() || 'Unknown gallery save error';
      throw new Error(`Gallery save error: ${message}`);
    }

    lastStatus = ((await status.textContent()) ?? '').trim();
    if (lastStatus === 'Saved.') {
      return;
    }

    const canClickSave = await saveButton.isEnabled().catch(() => false);
    const unsaved = /^Unsaved changes\./i.test(lastStatus);
    if (unsaved || canClickSave) {
      let canClickNow = canClickSave;
      if (!canClickNow) {
        const readiness = await waitForManualSaveReady();
        lastStatus = readiness.statusText;
        if (!/^Unsaved changes\./i.test(lastStatus)) {
          continue;
        }
        canClickNow = readiness.canClick;
      }
      if (!canClickNow) {
        await page.waitForTimeout(300);
        continue;
      }

      try {
        await expect(saveButton).toBeEnabled({ timeout: 2_000 });
      } catch {
        await page.waitForTimeout(300);
        continue;
      }

      const saveRequest = waitForFlightPlanPatch(page, slug);
      try {
        await saveButton.click({ timeout: 5_000 });
      } catch (error: unknown) {
        const message = error instanceof Error ? error.message : String(error);
        if (/not enabled|Timeout/i.test(message)) {
          await page.waitForTimeout(300);
          continue;
        }
        throw error;
      }
      await saveRequest;
      await page.waitForTimeout(300);
      continue;
    }

    await page.waitForTimeout(500);
  }

  throw new Error(`Gallery save state did not settle (last status: ${lastStatus || 'unknown'}).`);
};

test.describe('Gallery persistence regressions', () => {
  test.describe.configure({ timeout: GALLERY_SPEC_TIMEOUT_MS });

  test('flight plan gallery persists upload, move, remove, manual save, and reload', async ({
    page,
    request,
  }) => {
    let captain: SeededAccount;
    try {
      captain = getSeededCaptain();
    } catch (error: unknown) {
      test.skip(String(error));
      return;
    }

    const session = await loginViaApi(request, captain);
    const token = session.token ?? '';
    expect(token, 'captain login should return bearer token').toBeTruthy();

    const stamp = Date.now();
    const { slug } = await createFlightPlan(request, token, stamp);
    const persistedTitle = `Persisted slide ${stamp}`;

    try {
      await loginThroughUi(page, captain, { landingPath: `/bridge/flight-plans/${slug}` });
      await ensureFlightPlanAccess(page, captain, slug);
      await recoverTransientFlightPlanFetchFailure(page, slug);

      const editor = page.locator('.flight-plan-gallery-editor');
      await expect(editor).toBeVisible({ timeout: 30_000 });
      await keepSessionAlive(page);

      const fileInput = editor.locator('input[type="file"]').first();
      await uploadFlightPlanImageWithRetry({
        page,
        editor,
        fileInput,
        stamp,
        suffix: 'a',
        expectedCount: 1,
      });
      await uploadFlightPlanImageWithRetry({
        page,
        editor,
        fileInput,
        stamp,
        suffix: 'b',
        expectedCount: 2,
      });
      await persistFlightPlanGalleryChanges(page, editor, slug);

      const slideCards = editor.locator('.gallery-slide-editor');
      const firstSlide = slideCards.nth(0);
      await expandAccordionItem(firstSlide);
      await firstSlide.getByLabel('Title').fill(persistedTitle);
      await expect(editor.locator('.flight-plan-gallery-editor__save .ui-text').first()).toHaveText(
        'Unsaved changes.',
      );

      await persistFlightPlanGalleryChanges(page, editor, slug);

      const moveDownButton = firstSlide.getByRole('button', { name: 'Move down' });
      await expect(moveDownButton).toBeEnabled({ timeout: 30_000 });
      await moveDownButton.click();
      await persistFlightPlanGalleryChanges(page, editor, slug);

      const currentFirstSlide = editor.locator('.gallery-slide-editor').nth(0);
      await expandAccordionItem(currentFirstSlide);
      const removeButton = currentFirstSlide.getByRole('button', { name: 'Remove' });
      await expect(removeButton).toBeEnabled({ timeout: 30_000 });
      await removeButton.click();
      await persistFlightPlanGalleryChanges(page, editor, slug);

      await expect(editor.locator('.gallery-slide-editor')).toHaveCount(1, { timeout: 30_000 });

      await keepSessionAlive(page);
      await page.reload();
      await dismissSessionWarning(page);
      await ensureFlightPlanAccess(page, captain, slug);

      const missionGallery = page
        .locator('.gallery-section')
        .filter({ has: page.getByRole('heading', { name: 'Mission gallery' }) })
        .first();
      await expect(missionGallery).toBeVisible({ timeout: 30_000 });
      await expect(missionGallery.locator('.ui-carousel__slide strong')).toHaveText(
        persistedTitle,
        {
          timeout: 30_000,
        },
      );
      await expect(missionGallery.locator('.ui-carousel__dot')).toHaveCount(1);
    } finally {
      if (SHOULD_CLEANUP_DYNAMIC_FIXTURES) {
        await cleanupFlightPlan(request, token, slug);
      }
    }
  });

  test('static page carousel persists upload, move, remove, save, and reload', async ({
    page,
    request,
  }) => {
    let captain: SeededAccount;
    try {
      captain = getSeededCaptain();
    } catch (error: unknown) {
      test.skip(String(error));
      return;
    }

    const session = await loginViaApi(request, captain);
    const token = session.token ?? '';
    expect(token, 'captain login should return bearer token').toBeTruthy();

    const stamp = Date.now();
    const { id: pageId, path } = await createPageWithCarousel(request, token, stamp);
    const persistedAlt = `Static persisted alt ${stamp}`;

    try {
      await loginThroughUi(page, captain, { landingPath: `/${path}` });

      const editorHeading = page.getByRole('heading', { name: 'Edit page' });
      const editorError = page.locator('.page-editor__error').first();
      await openPageEditor(page);
      await keepSessionAlive(page);

      const carouselBlock = page
        .locator('.page-editor-block')
        .filter({ hasText: 'Image carousel' })
        .first();
      await expect(carouselBlock).toBeVisible({ timeout: 30_000 });

      const slideCards = carouselBlock.locator('.page-editor__carousel-slide');
      await expect(slideCards).toHaveCount(2, { timeout: 30_000 });

      const topUploadButton = carouselBlock.getByTestId('page-carousel-upload-button').first();
      const chooserPromise = page.waitForEvent('filechooser', { timeout: 30_000 });
      await topUploadButton.click();
      const chooser = await chooserPromise;
      await chooser.setFiles({
        name: `page-carousel-${stamp}.png`,
        mimeType: 'image/png',
        buffer: Buffer.from(PNG_1X1_BASE64, 'base64'),
      });
      await keepSessionAlive(page);
      await expect(carouselBlock.locator('.page-editor__carousel-slide')).toHaveCount(3, {
        timeout: 30_000,
      });

      const firstSlide = carouselBlock.locator('.page-editor__carousel-slide').first();
      await expandAccordionItem(firstSlide);
      const moveDownButton = firstSlide.getByRole('button', { name: 'Move down' });
      await expect(moveDownButton).toBeEnabled({ timeout: 30_000 });
      await moveDownButton.click();

      const currentFirstSlide = carouselBlock.locator('.page-editor__carousel-slide').first();
      await expandAccordionItem(currentFirstSlide);
      const removeButton = currentFirstSlide.getByRole('button', { name: 'Remove' });
      await expect(removeButton).toBeEnabled({ timeout: 30_000 });
      await removeButton.click();

      const nextFirstSlide = carouselBlock.locator('.page-editor__carousel-slide').first();
      await expandAccordionItem(nextFirstSlide);
      const removeSecondButton = nextFirstSlide.getByRole('button', { name: 'Remove' });
      await expect(removeSecondButton).toBeEnabled({ timeout: 30_000 });
      await removeSecondButton.click();

      const remainingSlide = carouselBlock.locator('.page-editor__carousel-slide').first();
      await expect(carouselBlock.locator('.page-editor__carousel-slide')).toHaveCount(1, {
        timeout: 30_000,
      });
      await expandAccordionItem(remainingSlide);
      await remainingSlide.getByLabel('Alt text').fill(persistedAlt);
      await waitForPageCarouselUploadsToFinish(carouselBlock);

      const pageSave = waitForPagePatch(page, pageId);
      await keepSessionAlive(page);
      await page.getByRole('button', { name: 'Save page' }).click();
      await pageSave;
      await expect(async () => {
        await keepSessionAlive(page);
        if (await editorError.isVisible().catch(() => false)) {
          throw new Error(
            `Page editor save failed: ${(await editorError.textContent())?.trim() || 'Unknown error'}`,
          );
        }
        await expect(editorHeading).not.toBeVisible({ timeout: 5_000 });
      }).toPass({ timeout: 45_000 });

      await keepSessionAlive(page);
      await page.reload();
      await dismissSessionWarning(page);

      const renderedCarousel = page.locator('.ui-carousel').first();
      await expect(renderedCarousel).toBeVisible({ timeout: 30_000 });
      await expect(renderedCarousel.locator('.ui-carousel__slide img')).toHaveAttribute(
        'alt',
        persistedAlt,
      );
      await expect(renderedCarousel.locator('.ui-carousel__dot')).toHaveCount(1);
    } finally {
      if (SHOULD_CLEANUP_DYNAMIC_FIXTURES) {
        await cleanupPage(request, token, pageId);
      }
    }
  });
});
