export const cssVariableTokens = {
  'font-family-display': "'Special Elite', system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif",
  'font-family-body': 'var(--font-family-display)',
  'font-family-mono':
    "ui-monospace, SFMono-Regular, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  'font-weight-regular': '400',
  'font-weight-medium': '500',
  'font-weight-semibold': '600',
  'line-height-body': '1.7',
  'color-background-base': '#000000',
  'color-background-page': '#000000',
  'color-surface-base': 'var(--color-surface-panel)',
  'color-surface-panel': 'rgba(255, 255, 255, 0.08)',
  'color-surface-panel-strong': 'rgba(15, 23, 42, 0.4)',
  'color-surface-overlay': 'rgba(0, 0, 0, 0.68)',
  'color-surface-overlay-strong': 'rgba(2, 4, 10, 0.78)',
  'color-surface-dialog': 'rgba(10, 10, 10, 0.95)',
  'color-surface-avatar': 'var(--color-surface-base)',
  'color-surface-toggle-off': 'rgba(255, 255, 255, 0.2)',
  'color-surface-muted': 'rgba(255, 255, 255, 0.05)',
  'color-surface-raised': 'rgba(255, 255, 255, 0.12)',
  'color-surface-secondary': 'var(--color-surface-panel)',
  'color-surface-tertiary': 'var(--color-surface-panel-strong)',
  'color-surface-hero': 'rgba(0, 0, 0, 0.35)',
  'color-surface-success-weak': 'rgba(34, 221, 0, 0.15)',
  'color-surface-warning-weak': 'rgba(255, 212, 0, 0.15)',
  'color-surface-danger-weak': 'rgba(251, 113, 133, 0.15)',
  'color-surface-info-weak': 'rgba(159, 214, 245, 0.15)',
  'color-border-strong': 'rgba(255, 255, 255, 0.35)',
  'color-border-weak': 'rgba(255, 255, 255, 0.2)',
  'color-border-panel': 'rgba(255, 255, 255, 0.12)',
  'color-border-panel-strong': 'rgba(255, 255, 255, 0.22)',
  'color-border-dialog': 'rgba(255, 255, 255, 0.18)',
  'color-border-contrast': 'rgba(255, 255, 255, 0.4)',
  'color-border-focus': 'rgba(159, 214, 245, 0.75)',
  'color-border-status-success': 'rgba(34, 221, 0, 0.35)',
  'color-border-status-warning': 'rgba(255, 212, 0, 0.35)',
  'color-border-status-danger': 'rgba(251, 113, 133, 0.35)',
  'color-border-status-info': 'rgba(159, 214, 245, 0.35)',
  'color-text-primary': '#ffffff',
  'color-text-secondary': 'rgba(255, 255, 255, 0.86)',
  'color-text-muted': 'rgba(255, 255, 255, 0.7)',
  'color-text-meta': 'var(--color-text-muted)',
  'color-text-caption': 'var(--color-text-faint)',
  'color-text-faint': 'rgba(255, 255, 255, 0.6)',
  'color-text-inverse': 'rgba(12, 15, 25, 0.95)',
  'color-accent-primary': '#ff0040',
  'color-accent-secondary': '#00c0ff',
  'color-accent-tertiary': '#ffd400',
  'color-success': '#22dd00',
  'color-warning': '#ffd400',
  'color-danger': '#fb7185',
  'color-info': '#9fd6f5',
  'gradient-button-default': 'linear-gradient(135deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0.05))',
  'gradient-button-hover': 'linear-gradient(135deg, rgba(255, 255, 255, 0.35), rgba(255, 255, 255, 0.1))',
  'gradient-rainbow': 'linear-gradient(90deg, #ff0040, #ff8000, #ffd400, #22dd00, #00c0ff, #6a00ff, #ff00c8, #ff0040)',
  'gradient-profile-haze': 'linear-gradient(180deg, rgba(6, 16, 24, 0.82), rgba(6, 16, 24, 0.96))',
  'gradient-profile-radial': 'radial-gradient(circle at 20% 20%, rgba(6, 16, 24, 0.6), rgba(3, 6, 12, 0.9))',
  'gradient-badge-dark': 'linear-gradient(145deg, rgba(11, 31, 54, 0.95), rgba(7, 14, 28, 0.95))',
  'gradient-badge-fallback': 'linear-gradient(135deg, rgba(255, 255, 255, 0.18), rgba(255, 255, 255, 0.05))',
  'gradient-skeleton': 'linear-gradient(90deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.05))',
  'gradient-portrait-background': 'radial-gradient(circle at 30% 30%, rgba(130, 210, 255, 0.65), rgba(34, 74, 112, 0.6))',
  'gradient-portrait-overlay': 'linear-gradient(175deg, rgba(6, 16, 24, 0.82), rgba(6, 16, 24, 0.1) 65%, rgba(6, 16, 24, 0))',
  'gradient-portrait-fallback': 'linear-gradient(140deg, rgba(255, 255, 255, 0.9), rgba(110, 168, 214, 0.6))',
  'gradient-media-caption': 'linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.85) 100%)',
  'color-button-border': 'var(--color-border-strong)',
  'color-button-border-hover': 'rgba(255, 255, 255, 0.6)',
  'color-button-secondary-border': 'rgba(255, 255, 255, 0.2)',
  'color-button-secondary-background': 'rgba(255, 255, 255, 0.05)',
  'color-badge-background': 'rgba(255, 255, 255, 0.12)',
  'color-field-background': 'rgba(255, 255, 255, 0.08)',
  'color-field-border': 'rgba(255, 255, 255, 0.2)',
  'color-field-border-strong': 'rgba(207, 237, 255, 0.22)',
  'color-field-background-inset': 'rgba(0, 0, 0, 0.35)',
  'color-task-ideation': 'var(--color-accent-secondary)',
  'color-task-grooming': 'var(--color-accent-tertiary)',
  'color-task-ready': 'var(--color-info)',
  'color-task-in-progress': 'var(--color-accent-primary)',
  'color-task-review': 'var(--color-warning)',
  'color-task-done': 'var(--color-success)',
  'color-task-live': '#4be3ff',
  'color-data-series-alpha': '#4be3ff',
  'color-data-series-beta': '#ff7b52',
  'color-data-series-gamma': '#ffd400',
  'color-data-series-delta': '#b48bff',
  'color-data-surface': 'rgba(255, 255, 255, 0.06)',
  'color-data-axis': 'rgba(255, 255, 255, 0.35)',
  'color-data-gridline': 'rgba(255, 255, 255, 0.18)',
  'color-data-neutral': 'rgba(255, 255, 255, 0.75)',
  'size-base-icon-px': '32px',
  'size-scale-factor': '1',
  'size-base-space-rem': '1rem',
  'size-base-radius-px': '1px',
  'size-base-layout-px': '1px',
  'size-avatar-xs': 'calc(var(--icon-size-px) * 1.3125)',
  'size-avatar-sm': 'calc(var(--icon-size-px) * 1.5)',
  'size-avatar-md': 'calc(var(--icon-size-px) * 2.125)',
  'size-avatar-lg': 'calc(var(--icon-size-px) * 2.6875)',
  'size-avatar-xl': 'calc(var(--icon-size-px) * 3.5)',
  'size-avatar-2xl': 'calc(var(--icon-size-px) * 4)',
  'size-avatar-hero': 'calc(var(--icon-size-px) * 4.125)',
  'size-avatar-hero-compact': 'calc(var(--icon-size-px) * 3.4375)',
  'size-badge-xs': 'calc(var(--icon-size-px) * 0.6)',
  'size-badge-sm': 'calc(var(--icon-size-px) * 0.75)',
  'size-badge-md': 'calc(var(--icon-size-px) * 0.85)',
  'size-ratio-menu-to-avatar-hero': '0.58',
  'size-ratio-badge-to-avatar-hero': '0.2061',
  'size-ratio-badge-to-avatar-chip': '0.5667',
  'size-ratio-badge-anchor-offset-to-avatar': '0.15',
  'size-menu-object': 'calc(var(--size-avatar-hero) * var(--size-ratio-menu-to-avatar-hero))',
  'size-flag-reference': 'var(--size-avatar-hero)',
  'size-runtime-avatar-hero-px': 'var(--size-avatar-hero)',
  'size-runtime-badge-md-px': 'var(--size-badge-md)',
  'size-runtime-menu-object-px': 'var(--size-menu-object)',
  'space-3xs': 'calc(var(--size-base-space-rem) * 0.125 * var(--size-scale-factor))',
  'space-xxs': 'calc(var(--size-base-space-rem) * 0.1875 * var(--size-scale-factor))',
  'space-2xs': 'calc(var(--size-base-space-rem) * 0.25 * var(--size-scale-factor))',
  'space-xs': 'calc(var(--size-base-space-rem) * 0.5 * var(--size-scale-factor))',
  'space-sm': 'calc(var(--size-base-space-rem) * 0.75 * var(--size-scale-factor))',
  'space-md': 'calc(var(--size-base-space-rem) * 1 * var(--size-scale-factor))',
  'space-lg': 'calc(var(--size-base-space-rem) * 1.5 * var(--size-scale-factor))',
  'space-xl': 'calc(var(--size-base-space-rem) * 2 * var(--size-scale-factor))',
  'space-2xl': 'calc(var(--size-base-space-rem) * 3 * var(--size-scale-factor))',
  'layout-page-gap': 'calc(var(--size-base-layout-px) * 48 * var(--size-scale-factor))',
  'layout-section-gap': 'calc(var(--size-base-layout-px) * 32 * var(--size-scale-factor))',
  'layout-card-padding': 'calc(var(--size-base-layout-px) * 24 * var(--size-scale-factor))',
  'layout-card-radius': 'var(--radius-lg)',
  'radius-control': 'var(--radius-sm)',
  'radius-sm': 'calc(var(--size-base-radius-px) * 10 * var(--size-scale-factor))',
  'radius-md': 'calc(var(--size-base-radius-px) * 14 * var(--size-scale-factor))',
  'radius-lg': 'calc(var(--size-base-radius-px) * 18 * var(--size-scale-factor))',
  'radius-pill': '999px',
  'shadow-card': '0 12px 30px rgba(0, 0, 0, 0.25)',
  'shadow-overlay': '0 24px 64px rgba(0, 0, 0, 0.45)',
  'shadow-glow-success': '0 0 18px rgba(61, 220, 151, 0.45)',
  'shadow-glow-danger': '0 0 10px rgba(242, 87, 87, 0.25)',
  'shadow-glow-warning': '0 0 12px rgba(250, 204, 21, 0.5)',
  'shadow-text-contrast': '0 2px 8px rgba(0, 0, 0, 0.45)',
  'transition-duration-base': '0.2s',
  'animation-duration-short': '120ms',
  'animation-duration-medium': '220ms',
  'animation-duration-long': '420ms',
  'transition-ease-standard': 'ease',
  'icon-size-px': 'calc(var(--size-base-icon-px) * var(--size-scale-factor))',
  'clip-top': 'calc(var(--icon-size-px) * 1)',
  'clip-bottom': 'calc(var(--icon-size-px) * 1)',
  'fade-size': 'calc(var(--icon-size-px) * 2)',
  'content-panel-blur': 'calc(var(--icon-size-px) * 1)',
  'content-panel-padding': 'clamp(2rem, 6vw, 3rem)',
  'status-toggle-diameter-base': 'var(--icon-size-px)',
  'status-toggle-indent-base': 'calc(var(--size-base-space-rem) * 1.75 * var(--size-scale-factor))',
  'z-overlay-drawer': '2900',
  'z-overlay-modal': '3000',
  'z-overlay-popover': '3200',
  'z-overlay-tooltip': '3300',
  'z-overlay-context': '3500',
  'z-overlay-toast': '3600',
  'z-overlay-blocking': '4000',
  'font-top-padding': '0.002',
  'heading-size-h1': 'calc(var(--icon-size-px) * 1)',
  'heading-size-h2': 'calc(var(--icon-size-px) * 0.75)',
  'heading-size-h3': 'calc(var(--icon-size-px) * 0.6)',
  'heading-size-h4': 'calc(var(--icon-size-px) * 0.55)',
  'heading-size-h5': 'calc(var(--icon-size-px) * 0.525)',
  'heading-size-h6': 'calc(var(--icon-size-px) * 0.5)',
  'crew-identity-gap': '0.35rem',
  'crew-identity-meta-font-size': '0.7rem',
  'crew-identity-meta-letter-spacing': '0.08em',
  'crew-identity-meta-color': 'rgba(248, 249, 255, 0.65)',
  'crew-identity-meta-color-online': 'rgba(124, 242, 182, 0.9)',
} as const;

export type CssVariableTokenName = keyof typeof cssVariableTokens;

export const customMediaTokens = {
  'bp-max-compact': '(max-width: 37.5rem)',
  'bp-max-sm': '(max-width: 40rem)',
  'bp-max-md': '(max-width: 45rem)',
  'bp-max-lg': '(max-width: 48rem)',
  'bp-max-xl': '(max-width: 60rem)',
} as const;

export type CustomMediaTokenName = keyof typeof customMediaTokens;

export const semanticTokenBlueprint = {
  color: {
    background: {
      base: 'color-background-base',
      page: 'color-background-page',
      surfaceBase: 'color-surface-base',
      panel: 'color-surface-panel',
      panelStrong: 'color-surface-panel-strong',
      overlay: 'color-surface-overlay',
      overlayStrong: 'color-surface-overlay-strong',
      dialog: 'color-surface-dialog',
      hero: 'color-surface-hero',
    },
    surface: {
      base: 'color-surface-base',
      panel: 'color-surface-panel',
      panelStrong: 'color-surface-panel-strong',
      overlay: 'color-surface-overlay',
      overlayStrong: 'color-surface-overlay-strong',
      dialog: 'color-surface-dialog',
      muted: 'color-surface-muted',
      raised: 'color-surface-raised',
      avatar: 'color-surface-avatar',
      toggleOff: 'color-surface-toggle-off',
      statusWeak: {
        success: 'color-surface-success-weak',
        warning: 'color-surface-warning-weak',
        danger: 'color-surface-danger-weak',
        info: 'color-surface-info-weak',
      },
    },
    border: {
      strong: 'color-border-strong',
      weak: 'color-border-weak',
      panel: 'color-border-panel',
      panelStrong: 'color-border-panel-strong',
      dialog: 'color-border-dialog',
      contrast: 'color-border-contrast',
      focus: 'color-border-focus',
      status: {
        success: 'color-border-status-success',
        warning: 'color-border-status-warning',
        danger: 'color-border-status-danger',
        info: 'color-border-status-info',
      },
    },
    text: {
      primary: 'color-text-primary',
      secondary: 'color-text-secondary',
      muted: 'color-text-muted',
      meta: 'color-text-meta',
      caption: 'color-text-caption',
      faint: 'color-text-faint',
      inverse: 'color-text-inverse',
    },
    accent: {
      primary: 'color-accent-primary',
      secondary: 'color-accent-secondary',
      tertiary: 'color-accent-tertiary',
    },
    feedback: {
      success: 'color-success',
      warning: 'color-warning',
      danger: 'color-danger',
      info: 'color-info',
    },
    field: {
      background: 'color-field-background',
      border: 'color-field-border',
      borderStrong: 'color-field-border-strong',
      backgroundInset: 'color-field-background-inset',
    },
    badge: {
      background: 'color-badge-background',
    },
    button: {
      border: 'color-button-border',
      borderHover: 'color-button-border-hover',
      secondaryBorder: 'color-button-secondary-border',
      secondaryBackground: 'color-button-secondary-background',
    },
  },
  gradient: {
    buttonDefault: 'gradient-button-default',
    buttonHover: 'gradient-button-hover',
    rainbow: 'gradient-rainbow',
    profile: {
      haze: 'gradient-profile-haze',
      radial: 'gradient-profile-radial',
    },
    badge: {
      dark: 'gradient-badge-dark',
      fallback: 'gradient-badge-fallback',
    },
    skeleton: 'gradient-skeleton',
    portrait: {
      background: 'gradient-portrait-background',
      overlay: 'gradient-portrait-overlay',
      fallback: 'gradient-portrait-fallback',
    },
    mediaCaption: 'gradient-media-caption',
  },
  spacing: {
    '3xs': 'space-3xs',
    xxs: 'space-xxs',
    '2xs': 'space-2xs',
    xs: 'space-xs',
    sm: 'space-sm',
    md: 'space-md',
    lg: 'space-lg',
    xl: 'space-xl',
    '2xl': 'space-2xl',
  },
  size: {
    core: {
      baseIconPx: 'size-base-icon-px',
      scaleFactor: 'size-scale-factor',
      baseSpaceRem: 'size-base-space-rem',
      baseRadiusPx: 'size-base-radius-px',
      baseLayoutPx: 'size-base-layout-px',
    },
    role: {
      avatar: {
        xs: 'size-avatar-xs',
        sm: 'size-avatar-sm',
        md: 'size-avatar-md',
        lg: 'size-avatar-lg',
        xl: 'size-avatar-xl',
        '2xl': 'size-avatar-2xl',
        hero: 'size-avatar-hero',
        heroCompact: 'size-avatar-hero-compact',
      },
      badge: {
        xs: 'size-badge-xs',
        sm: 'size-badge-sm',
        md: 'size-badge-md',
      },
      menuObject: 'size-menu-object',
      flagReference: 'size-flag-reference',
    },
    relation: {
      menuToAvatarHero: 'size-ratio-menu-to-avatar-hero',
      badgeToAvatarHero: 'size-ratio-badge-to-avatar-hero',
      badgeToAvatarChip: 'size-ratio-badge-to-avatar-chip',
      badgeAnchorOffsetToAvatar: 'size-ratio-badge-anchor-offset-to-avatar',
    },
  },
  radius: {
    control: 'radius-control',
    sm: 'radius-sm',
    md: 'radius-md',
    lg: 'radius-lg',
    pill: 'radius-pill',
  },
  shadow: {
    card: 'shadow-card',
    overlay: 'shadow-overlay',
    glow: {
      success: 'shadow-glow-success',
      warning: 'shadow-glow-warning',
      danger: 'shadow-glow-danger',
    },
    textContrast: 'shadow-text-contrast',
  },
  font: {
    family: {
      display: 'font-family-display',
      body: 'font-family-body',
      mono: 'font-family-mono',
    },
    weight: {
      regular: 'font-weight-regular',
      medium: 'font-weight-medium',
      semibold: 'font-weight-semibold',
    },
    lineHeight: {
      body: 'line-height-body',
    },
  },
  component: {
    button: {
      border: 'color-button-border',
      borderHover: 'color-button-border-hover',
      secondaryBorder: 'color-button-secondary-border',
      secondaryBackground: 'color-button-secondary-background',
    },
    field: {
      background: 'color-field-background',
      border: 'color-field-border',
      backgroundInset: 'color-field-background-inset',
    },
    task: {
      ideation: 'color-task-ideation',
      grooming: 'color-task-grooming',
      ready: 'color-task-ready',
      inProgress: 'color-task-in-progress',
      review: 'color-task-review',
      done: 'color-task-done',
      live: 'color-task-live',
    },
  },
  layout: {
    iconSize: 'icon-size-px',
    clipTop: 'clip-top',
    clipBottom: 'clip-bottom',
    fadeSize: 'fade-size',
    contentPanelBlur: 'content-panel-blur',
    contentPanelPadding: 'content-panel-padding',
    pageGap: 'layout-page-gap',
    sectionGap: 'layout-section-gap',
    cardPadding: 'layout-card-padding',
    cardRadius: 'layout-card-radius',
  },
  animation: {
    duration: {
      short: 'animation-duration-short',
      medium: 'animation-duration-medium',
      long: 'animation-duration-long',
    },
  },
  zIndex: {
    drawer: 'z-overlay-drawer',
    modal: 'z-overlay-modal',
    popover: 'z-overlay-popover',
    tooltip: 'z-overlay-tooltip',
    contextMenu: 'z-overlay-context',
    toast: 'z-overlay-toast',
    blocking: 'z-overlay-blocking',
  },
  dataViz: {
    surface: 'color-data-surface',
    axis: 'color-data-axis',
    gridline: 'color-data-gridline',
    neutral: 'color-data-neutral',
    series: {
      alpha: 'color-data-series-alpha',
      beta: 'color-data-series-beta',
      gamma: 'color-data-series-gamma',
      delta: 'color-data-series-delta',
    },
  },
} as const;

export type SemanticTokenBlueprint = typeof semanticTokenBlueprint;
