import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'index.ts',
    accessPolicy: 'accessPolicy.ts',
    crewRoles: 'crewRoles.ts',
    adminMode: 'adminMode.ts',
    authorization: 'authorization.ts',
    permissions: 'permissions.ts',
    'api-contracts': 'api-contracts.ts',
    honorBadges: 'honorBadges.ts',
    pageBlocks: 'pageBlocks.ts',
    logs: 'logs.ts',
    navigationNodes: 'navigationNodes.ts',
    mediaUrls: 'mediaUrls.ts',
    avatarMedia: 'avatarMedia.ts',
    flightPlanLifecycle: 'flightPlanLifecycle.ts',
    galleryMedia: 'galleryMedia.ts',
    plans: 'plans.ts',
    env: 'env.ts',
    taskStates: 'taskStates.ts',
    roadmap: 'roadmap.ts',
    'theme/tokens': 'theme/tokens.ts',
    'theme/runtime-tokens': 'theme/runtime-tokens.ts',
  },
  format: ['esm'],
  target: 'es2022',
  dts: true,
  sourcemap: false,
  outDir: 'dist',
  clean: false,
  splitting: false,
  treeshake: true,
  platform: 'neutral',
  external: ['zod'],
  tsconfig: 'tsconfig.build.json',
  outExtension: () => ({ js: '.mjs' }),
  shims: false,
});
